<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PRODUCT MANAGEMENT PRODUCT MANAGEMENTProd_ec13a1</name>
   <tag></tag>
   <elementGuidId>ba4904b9-f7c3-4e62-9d56-ae4bbc84d321</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='products_anchor']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#products_anchor</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Product Management&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4413fb28-9760-4308-be4e-65b42f1c221f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hov main-menu</value>
      <webElementGuid>b783cf41-56f4-42c3-bff6-62466fb565e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>272cddf1-742e-4f1c-ab52-f5f58fdb4a66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Product Management</value>
      <webElementGuid>4f13fae3-c236-454e-a2a2-665335d72ff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>products_anchor</value>
      <webElementGuid>cb6dfc1d-fa70-4097-a11f-1db36e7225bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PRODUCT MANAGEMENT PRODUCT MANAGEMENTProduct CatalogProduct MasterProduct AliasUOM ConversionBrand Store Attribute Mapping Hierarchy TypeHierarchy Creation</value>
      <webElementGuid>06866ff7-373f-43d4-9393-6269e2bb75c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;products_anchor&quot;)</value>
      <webElementGuid>685832ea-8e64-49ec-8cfd-37b09229e995</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='products_anchor']</value>
      <webElementGuid>d271bb02-abf6-4310-8461-602562a6d52d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sidebar-nav-id']/li[6]/a</value>
      <webElementGuid>9d2519dd-bb2a-4f5d-85d0-d6ec0aab1ce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stock Take'])[1]/following::a[1]</value>
      <webElementGuid>a3ed8972-2970-45da-a138-defa8e8796ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cost List'])[1]/following::a[2]</value>
      <webElementGuid>f9dba06a-a604-4ac0-9dfb-7f9fb4abefb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[9]</value>
      <webElementGuid>7682eaf5-4a2d-41be-aed3-4cb53728e7f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>dc006ad1-e114-4e6e-a78f-92fcae4e92ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @title = 'Product Management' and @id = 'products_anchor' and (text() = 'PRODUCT MANAGEMENT PRODUCT MANAGEMENTProduct CatalogProduct MasterProduct AliasUOM ConversionBrand Store Attribute Mapping Hierarchy TypeHierarchy Creation' or . = 'PRODUCT MANAGEMENT PRODUCT MANAGEMENTProduct CatalogProduct MasterProduct AliasUOM ConversionBrand Store Attribute Mapping Hierarchy TypeHierarchy Creation')]</value>
      <webElementGuid>7067590a-398a-4053-9947-bc0e005085ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
