<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SELECT</name>
   <tag></tag>
   <elementGuidId>df5c961e-ff8d-4187-8f15-1efb9a4448a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='table1']/td[7]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#table1 > td.text-center > div.hover-contents > button.select-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;SELECT&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3e662181-0ff1-4db3-abca-7bf1cff4b85a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-btn</value>
      <webElementGuid>03342603-79f8-48f7-80eb-911eee9d4c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SELECT</value>
      <webElementGuid>5b92a77a-f1fe-4ed3-b493-1c8646d00c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table1&quot;)/td[@class=&quot;text-center&quot;]/div[@class=&quot;hover-contents&quot;]/button[@class=&quot;select-btn&quot;]</value>
      <webElementGuid>460c9c01-cd0d-4a44-8bd0-fa68d4fd6be6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='table1']/td[7]/div/button</value>
      <webElementGuid>6b06be52-7c43-4f4f-b5e0-9b4b579b2457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bowl'])[2]/following::button[1]</value>
      <webElementGuid>09d33522-6fd9-49fd-953b-e53a4a9daf89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Casual Shoes for Mens 4321'])[1]/following::button[1]</value>
      <webElementGuid>ac4df960-7ef1-4b4d-a339-64a20aa90f8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product For TEst 03072024004!'])[1]/preceding::button[1]</value>
      <webElementGuid>a945cb98-e820-4523-8958-660639b55f17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Box'])[1]/preceding::button[1]</value>
      <webElementGuid>e14d27a3-6bc0-4097-92b1-b1b95441b00d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[7]/div/button</value>
      <webElementGuid>a9b1f4c2-7629-4851-89c3-a4f52c909a05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'SELECT' or . = 'SELECT')]</value>
      <webElementGuid>fd7f3c39-ccbc-4acb-8545-3b7efafe0aa6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
