<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ALTERNATE UOM VALUE_hb-add-icon-btn</name>
   <tag></tag>
   <elementGuidId>f1656d13-b995-4983-969a-fdd86e298704</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='uom-list-main-div']/div[2]/div[4]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.hb-add-icon-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.hb-add-icon-btn</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e0762243-34f3-40f5-b56e-8221e774f8ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hb-add-icon-btn</value>
      <webElementGuid>75802bfa-5f63-4a5b-bb27-356d1f28db2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uom-list-main-div&quot;)/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;user-list-pos-relative&quot;]/button[@class=&quot;hb-add-icon-btn&quot;]</value>
      <webElementGuid>bb724d1c-1687-464c-a2b1-f6e6e85c1586</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uom-list-main-div']/div[2]/div[4]/button</value>
      <webElementGuid>c69391a6-04f1-4fee-8acb-3ab7935141dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/button</value>
      <webElementGuid>462bc423-eaf8-4a87-81a8-2324e2258846</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
