<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Charge Model is are Not Configured For _79ec56</name>
   <tag></tag>
   <elementGuidId>ec3358f6-6fa9-40d4-898b-aa1d94eec2d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cdk-overlay-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cdk-overlay-1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>df69b03f-6660-4aad-88a6-d52ef0b5d6e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cdk-overlay-1</value>
      <webElementGuid>82039c17-86da-4d93-a70b-83487ff46a62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cdk-overlay-pane</value>
      <webElementGuid>82a23891-fdbe-4629-aeb7-aba5d1fd125c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Charge Model is are Not Configured For Product, Please Configured Before Proceed!</value>
      <webElementGuid>c6ef1e2a-72ed-4a59-af86-4702e35a68dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-1&quot;)</value>
      <webElementGuid>55c51233-ddff-43a4-bd06-75f8fe99dd92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-1']</value>
      <webElementGuid>a140ca6f-2f52-4519-82b8-acdb833bc243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Charge Model is are Not Configured For Product, Please Configured Before Proceed!'])[1]/following::div[4]</value>
      <webElementGuid>c6d8e34d-bd9b-4332-856e-76d8843ba032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div</value>
      <webElementGuid>6a85ce2d-4c1f-4c46-95b7-8c829f6484c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'cdk-overlay-1' and (text() = 'Charge Model is are Not Configured For Product, Please Configured Before Proceed!' or . = 'Charge Model is are Not Configured For Product, Please Configured Before Proceed!')]</value>
      <webElementGuid>43caf9c2-410f-43a0-aff6-ce357a0f5a70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
