<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Charge Model is are Not Configured For _79ec56_1</name>
   <tag></tag>
   <elementGuidId>524b40c6-819d-4a2f-8788-17423e35e74a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cdk-overlay-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cdk-overlay-3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d71a3497-7a34-4c28-acd0-3b1fb750c682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cdk-overlay-3</value>
      <webElementGuid>f43891d5-25a6-48bc-9002-64e9d90942da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cdk-overlay-pane</value>
      <webElementGuid>30774ed7-9760-4f3e-b231-f6ec56b208c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Charge Model is are Not Configured For Product, Please Configured Before Proceed!</value>
      <webElementGuid>4b72c8d6-7340-47da-a9e8-a75a76b152b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-3&quot;)</value>
      <webElementGuid>d5ce0643-5c9c-4a3f-a4bc-2c7e7257d0e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-3']</value>
      <webElementGuid>238076fc-937f-44d5-9cd9-35fb8c2f00df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Charge Model is are Not Configured For Product, Please Configured Before Proceed!'])[1]/following::div[4]</value>
      <webElementGuid>fb9dcbe0-f6b5-401f-b740-abfc84d79e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div</value>
      <webElementGuid>fcdc8982-4bff-4475-989d-a1027c0461b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'cdk-overlay-3' and (text() = 'Charge Model is are Not Configured For Product, Please Configured Before Proceed!' or . = 'Charge Model is are Not Configured For Product, Please Configured Before Proceed!')]</value>
      <webElementGuid>936c9be0-6b98-48bb-bc5f-2bd07f0bc8c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
