<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_--Select Product Sub Category--</name>
   <tag></tag>
   <elementGuidId>d1ec883f-429b-4486-98aa-7d7c915536e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-select[@id='productSubCategory']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#productSubCategory > div.mat-select-trigger > div.mat-select-value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;--Select Product Sub Category--&quot;i >> div >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>621de4cd-ab1c-4c87-9bf1-810c69a3d4ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-value</value>
      <webElementGuid>100ad498-0c75-4459-aeef-a74397c81448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-switch</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4f06ec5b-ee55-494c-80fc-3654906c80af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select Product Sub Category--</value>
      <webElementGuid>c4ea4ee7-dd66-44c2-a20b-f073ab6ebbf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productSubCategory&quot;)/div[@class=&quot;mat-select-trigger&quot;]/div[@class=&quot;mat-select-value&quot;]</value>
      <webElementGuid>6512c746-f09b-4085-a065-1e502f5cd297</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='productSubCategory']/div/div</value>
      <webElementGuid>9f5fd535-74bc-45e3-a31d-f37f05dc68a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::div[2]</value>
      <webElementGuid>58f90830-a1ab-4a13-aec9-d123104b8559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/mat-select/div/div</value>
      <webElementGuid>0a48d160-40d7-4046-a257-513e15ca092c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '--Select Product Sub Category--' or . = '--Select Product Sub Category--')]</value>
      <webElementGuid>a30f4600-c087-49d6-ab2c-c9a85bdb823b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
