<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_APPLYCLEAR</name>
   <tag></tag>
   <elementGuidId>b85efff8-1be2-4ef7-adcc-b677e2879e7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='productTable']/thead/tr/td[5]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.nav_btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;APPLYCLEAR&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5fb988d6-ee24-46c9-b32f-2900d1e1e4fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav_btn</value>
      <webElementGuid>d93852fb-9006-45c9-989b-584b660e6064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> APPLYCLEAR</value>
      <webElementGuid>85666d7e-9364-4e02-80b5-af53a0980dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_table_parent&quot;)/table[@id=&quot;productTable&quot;]/thead[@class=&quot;fixed-head&quot;]/tr[1]/td[5]/div[@class=&quot;nav_btn&quot;]</value>
      <webElementGuid>bd8c5326-a15b-4c27-9011-0a101fde25d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='productTable']/thead/tr/td[5]/div</value>
      <webElementGuid>aa2ee644-f428-4289-9262-8ed4afcb9b76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Units of Measurement'])[1]/following::div[5]</value>
      <webElementGuid>373512f2-6196-486c-bb0f-052914a2ecc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick Product Lookup'])[1]/following::div[16]</value>
      <webElementGuid>4c6a7218-8803-4b72-ac95-8b0f602da389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div</value>
      <webElementGuid>1d4861e8-7fd4-42d2-820e-d3c7fdab195e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' APPLYCLEAR' or . = ' APPLYCLEAR')]</value>
      <webElementGuid>b5bc96ed-4726-40a7-9ffc-b7836c4d1b1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
