<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_MUM1</name>
   <tag></tag>
   <elementGuidId>70be235c-b2b8-4888-b761-6851b4399010</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='counter_selection_modal']/div[5]/div[2]/div[2]/div[3]/div/div/div/div/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.c_code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;MUM1&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2eab9b55-f67a-4762-93eb-17b72f30a2f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c_code</value>
      <webElementGuid>2de52a19-4265-472c-8fff-7e45017b7a6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-klass</name>
      <type>Main</type>
      <value>c_code</value>
      <webElementGuid>43a30961-4197-4a97-9018-cf8c8fbc0982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> MUM1 </value>
      <webElementGuid>737cc61d-41c6-49b6-8113-1461a269f9bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;counter_selection_modal&quot;)/div[5]/div[@class=&quot;col-sm-10 col-md-10 col-lg-8 col-xs-10 no-padding&quot;]/div[@class=&quot;col-lg-12 col-sm-12 col-md-12 middle-height ng-star-inserted&quot;]/div[@class=&quot;col-lg-12 col-sm-12 col-md-12 no-padding&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;col-sm-12 col-md-6 col-lg-6 col-xl-4 hb-no-padding company-list-card-padding ng-star-inserted&quot;]/div[@class=&quot;card-box&quot;]/div[1]/div[@class=&quot;Second_div1&quot;]/div[@class=&quot;c_code&quot;]</value>
      <webElementGuid>6fdb8ef3-ae6a-4f01-ba90-c0ad1639de07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='counter_selection_modal']/div[5]/div[2]/div[2]/div[3]/div/div/div/div/div[2]/div[2]</value>
      <webElementGuid>f0f72c00-860a-47e0-89a1-8a6bb14e47af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mumbai Store 1'])[1]/following::div[1]</value>
      <webElementGuid>4a7e04e4-88b9-4554-90e6-bd4d1b033d2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sylphy Corp1'])[1]/following::div[10]</value>
      <webElementGuid>08883907-e88e-49c3-8cfc-31607f473e04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mumbai Store 10'])[1]/preceding::div[2]</value>
      <webElementGuid>53739e3e-7b0d-471b-9c8b-06f3970b1d01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MUM10'])[1]/preceding::div[3]</value>
      <webElementGuid>5fa7941b-59e3-4733-8b40-8ffcc6185557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MUM1']/parent::*</value>
      <webElementGuid>f295093a-72a4-4eb0-8fad-dbab3190b367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/div[2]</value>
      <webElementGuid>0d169241-5954-4fbb-b09f-d574a19c4981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' MUM1 ' or . = ' MUM1 ')]</value>
      <webElementGuid>ecffba6e-817a-4a4b-802b-581b67dfe697</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
