<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_counter2975  C2975</name>
   <tag></tag>
   <elementGuidId>7e8c5043-a48a-4de6-8264-b9720d56283a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='counterId']/div/div/div[2])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;counter2975 C2975&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a6fb6dd5-615c-4abc-8b0c-6543a88c3235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Second_div2</value>
      <webElementGuid>45338403-d85d-439d-b7b0-6457e02a40bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-klass</name>
      <type>Main</type>
      <value>Second_div2</value>
      <webElementGuid>ce908b23-ab3f-4c33-bc0a-0f38e94f0f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>Second_div2</value>
      <webElementGuid>021ea319-a386-4627-9404-6cbc5eb6afad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> counter2975  C2975   </value>
      <webElementGuid>7def80ef-a37b-4af8-85fb-2d2f6ffc8661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;counter_selection_modal&quot;)/div[5]/div[@class=&quot;col-sm-10 col-md-10 col-lg-8 col-xs-10 no-padding&quot;]/div[@class=&quot;col-lg-12 col-sm-12 col-md-12 middle-height ng-star-inserted&quot;]/div[@class=&quot;col-lg-12 col-sm-12 col-md-12 no-padding ng-star-inserted&quot;]/div[@id=&quot;counterId&quot;]/div[@class=&quot;card-box&quot;]/div[1]/div[@class=&quot;Second_div2&quot;]</value>
      <webElementGuid>cbe55846-e7f2-41ee-a2a1-a1bef7f78071</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='counterId']/div/div/div[2])[4]</value>
      <webElementGuid>bd9737ee-8d78-4f3e-862e-10c4be83fc64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C2973'])[1]/following::div[6]</value>
      <webElementGuid>2421dd46-e535-4a54-b94f-4a0b424b75f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='counter2973'])[1]/following::div[7]</value>
      <webElementGuid>6d40cd80-2b26-4b0b-a615-36543749c154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]/div/div/div[2]</value>
      <webElementGuid>f9a179ef-c4d2-4304-a744-1e0aea364601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' counter2975  C2975   ' or . = ' counter2975  C2975   ')]</value>
      <webElementGuid>7ba56bfd-1da2-4a9e-ac6f-4aa3bda02d3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
