<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_CHECKOUT</name>
   <tag></tag>
   <elementGuidId>c19c195b-3154-48e2-b7db-a2f082aa24a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='left']/div[2]/app-sell-actions/div/div/div[2]/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-12.col-sm-12.col-lg-12.check_out.enabledButton > div.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;CHECKOUT&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8e77aadc-ffd2-4bb4-b54f-3b14a1bd263b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>ee7545f7-66db-4931-bd18-e31a9e4fde69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-klass</name>
      <type>Main</type>
      <value>col-md-12 col-sm-12 col-lg-12</value>
      <webElementGuid>91e72628-3ae8-4bbd-af11-0a5c26148487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>check_out enabledButton</value>
      <webElementGuid>fc4eb270-04a5-4b97-9703-2b4b22a821be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> CHECKOUT </value>
      <webElementGuid>9ee74b2c-8a7f-4f11-b8f0-8d45860a7557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;left&quot;)/div[@class=&quot;ng-star-inserted&quot;]/app-sell-actions[1]/div[1]/div[@class=&quot;row br_t&quot;]/div[@class=&quot;col-md-3 col-sm-3 col-lg-3 pd_r_l&quot;]/div[@class=&quot;col-md-12 col-sm-12 col-lg-12 check_out enabledButton&quot;]/div[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>4d3b5378-e607-4250-9a07-038ee5f90145</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='left']/div[2]/app-sell-actions/div/div/div[2]/div[3]/div</value>
      <webElementGuid>e18a81da-091c-44cf-9e9a-dc2a1eb1f5fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Net Amount'])[1]/following::div[2]</value>
      <webElementGuid>1e9059a3-171b-4169-a1d1-0eac46002909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scan To Remove Products'])[1]/following::div[5]</value>
      <webElementGuid>51564f2b-66ca-4296-b382-b09082d99e1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sylphy Corp1'])[1]/preceding::div[2]</value>
      <webElementGuid>700c74ec-796b-44dd-a101-a372f8bf4e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mumbai India'])[1]/preceding::div[4]</value>
      <webElementGuid>59571bc3-6ec7-4657-9347-900a6dc3bc70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CHECKOUT']/parent::*</value>
      <webElementGuid>41b20285-3ec5-4848-b663-ec108cdfe679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-sell-actions/div/div/div[2]/div[3]/div</value>
      <webElementGuid>101d22a8-1a24-47f2-82ac-59a7a4bbf1a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' CHECKOUT ' or . = ' CHECKOUT ')]</value>
      <webElementGuid>544a894d-772d-4b35-b0b2-56a47e6f7b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='left']/div[2]/app-sell-actions/div/div/div[2]/div[3]</value>
      <webElementGuid>f38f73f1-7b18-4567-abb1-3abf9e0fc030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Net Amount'])[1]/following::div[1]</value>
      <webElementGuid>97373e49-885c-416c-8dde-7d0b8a9ff369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scan To Remove Products'])[1]/following::div[4]</value>
      <webElementGuid>b889c0ac-6af0-4b50-848c-82f81666906a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sylphy Corp1'])[1]/preceding::div[3]</value>
      <webElementGuid>9e3a2fef-b6c2-4ab2-8b39-b89f5badeea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-sell-actions/div/div/div[2]/div[3]</value>
      <webElementGuid>65007df6-ec02-4c03-886d-a08934a75d72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
