<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Select Company_logo-icon ng-star-inserted</name>
   <tag></tag>
   <elementGuidId>7c777b5f-dd6d-4c89-9b04-5a0bd7c30171</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='counter_selection_modal']/div[5]/div[2]/div[2]/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.logo-icon.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;brand-logo&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>492e4fdc-af67-42b5-b5a0-61b5fddd433f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>brand-logo</value>
      <webElementGuid>bf2e16a6-92e8-4311-9e4a-48c8d47320a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo-icon ng-star-inserted</value>
      <webElementGuid>824f6a32-b549-42b3-8fc0-41e3711afa50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.src='assets/images/defaultgroupimage.svg'</value>
      <webElementGuid>a1c85e91-7e75-42ef-9050-b91488729ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://test-unify-gw.etpgroup.sg/default/thanatos/1.0/iiif/2/be662bb4d2f791e1aa91fcea4aa046d1.jpg/full/full/0/default.jpg-ccVrrM4o5rfYx1gVRy7utT2tyExYfaQC3MCOIZ82MLZVQEdwjMxg1RzB161fsHc6J5iOtmL0DU1HkCamXIl6l9gDLK7aNwN62rVAzUTi+4lv3t6Ru8YAhQlGc328U+r9oNKgqAUijh43HzCpfRca1RX+hNf83xZzqfd6s+M5wzIolEx6cMceAOVUG9G5Q14n</value>
      <webElementGuid>0bd6584f-a4e7-4d0d-8499-d04d0af08e44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;counter_selection_modal&quot;)/div[5]/div[@class=&quot;col-sm-10 col-md-10 col-lg-8 col-xs-10 no-padding&quot;]/div[@class=&quot;col-lg-12 col-sm-12 col-md-12 middle-height ng-star-inserted&quot;]/div[@class=&quot;col-xl-3 col-lg-4 col-sm-4 col-xs-6 user-list-card-padding ng-star-inserted&quot;]/div[@class=&quot;user-list-card-list-tab bgactive&quot;]/div[@class=&quot;image_container respClass&quot;]/img[@class=&quot;logo-icon ng-star-inserted&quot;]</value>
      <webElementGuid>47b41220-9e4c-4f0e-b927-c891213cf92e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='counter_selection_modal']/div[5]/div[2]/div[2]/div/div/div/img</value>
      <webElementGuid>25dea7d9-63a3-43ab-b639-92015347a099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='brand-logo']</value>
      <webElementGuid>12083c67-8f57-4df9-b063-093d193ed014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/img</value>
      <webElementGuid>119dd398-65e6-455d-9917-45c43f46c9f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'brand-logo' and @src = 'https://test-unify-gw.etpgroup.sg/default/thanatos/1.0/iiif/2/be662bb4d2f791e1aa91fcea4aa046d1.jpg/full/full/0/default.jpg-ccVrrM4o5rfYx1gVRy7utT2tyExYfaQC3MCOIZ82MLZVQEdwjMxg1RzB161fsHc6J5iOtmL0DU1HkCamXIl6l9gDLK7aNwN62rVAzUTi+4lv3t6Ru8YAhQlGc328U+r9oNKgqAUijh43HzCpfRca1RX+hNf83xZzqfd6s+M5wzIolEx6cMceAOVUG9G5Q14n']</value>
      <webElementGuid>e36a3b14-f461-4fce-b790-0a4578b52417</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
