<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Digitial Receipt Setup_15img</name>
   <tag></tag>
   <elementGuidId>4d6a90ab-7e03-4520-84a7-e81217f353c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='15img']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#15img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;POS&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fac2e7e5-2b74-49cc-80f1-f39797957250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-menu-icons</value>
      <webElementGuid>d8cd50b9-3e02-4723-8d0f-07e3b4b66bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>15img</value>
      <webElementGuid>dc66e52d-3425-4982-bead-d91dc6896929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../assets/images/icons/POSicon.svg</value>
      <webElementGuid>da9171e1-1560-4cf1-a1d8-21752fa471a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;15img&quot;)</value>
      <webElementGuid>34e8e260-7dce-4163-b437-32e7bc2e22d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='15img']</value>
      <webElementGuid>52d0071f-2e86-4058-8c11-dcc9de027ac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='pos_anchor']/span/img</value>
      <webElementGuid>13a2d75c-4df7-4600-9fbb-4dd14b4206ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[14]/a/span/img</value>
      <webElementGuid>c9c54b22-746b-48bf-9288-8f871d9ade7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = '15img' and @src = '../assets/images/icons/POSicon.svg']</value>
      <webElementGuid>40cbb4f0-1c85-4c50-a434-65b093f1da87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
