<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__floatTextBox</name>
   <tag></tag>
   <elementGuidId>75bf452b-dbc4-49ac-bfa8-02ca3580a1b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='floatTextBox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#floatTextBox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#floatTextBox >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a38e495d-1d62-40a6-b9a4-40a2c82240f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-field-wid-ht form-control numeric-text-right ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>e1847b5b-7dbe-48ef-930e-94a6ee47fd45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>length</value>
      <webElementGuid>0c93d990-1ce0-454c-bd53-45a9af7d3e16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>floatTextBox</value>
      <webElementGuid>c0954a3c-96a3-4264-b177-e894510b2392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>28b8a59b-39ee-41d6-8dbb-2e780e298467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value=this.value.replace(/[^0-9]/g, '')</value>
      <webElementGuid>3522f6c5-fc12-4363-9fb1-2e30f0c548a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>f9a3d1cb-93e3-4567-9406-14b155a6bee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>length</value>
      <webElementGuid>3d65fc1b-eec5-4816-b73e-16f9cf2d0b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;test3&quot;)/div[1]/div[@class=&quot;row template-form-white-background template-form-inside-padding33 displFlex&quot;]/div[@class=&quot;col-md-9 col-sm-9 template-forms-inputs-labels no-padding&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;col-md-3 col-sm-3 col-lg-3 form-group ng-star-inserted&quot;]/input[@id=&quot;floatTextBox&quot;]</value>
      <webElementGuid>5106afa7-ae08-46de-ae9b-ca8bb9cf677d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='floatTextBox']</value>
      <webElementGuid>099bd345-543a-48be-a466-d62b6447bdbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='test3']/div/div[2]/div/div[9]/div/input</value>
      <webElementGuid>80cf7451-b179-4284-af7a-fe70a04d5965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/input</value>
      <webElementGuid>478298f9-3c18-4520-99c5-5c45a9314312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'floatTextBox']</value>
      <webElementGuid>a50e6029-bc56-414b-bd79-9154cfd1b7df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
