<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select Units of Measurement_Length</name>
   <tag></tag>
   <elementGuidId>cc9a8c17-7dbb-42f4-aca9-333ce9116c33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Length</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;salesPersonFirstDiv&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Length&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9b05c3e-ca51-4e84-b741-3645f8864655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>30a8c490-add0-4b2b-b680-b1b0a19b29fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control c_height textNumericPaddings c_ad_input fullwidth ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>ec401d4c-f22b-4245-a51f-561e43b6e5df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1073d10f-8209-4b39-be0f-0380057fbc86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>Length</value>
      <webElementGuid>e824b73c-102d-4ec7-81be-0a31889d464a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Length</value>
      <webElementGuid>35eac228-4913-40f1-bd5c-1ea1c9ad7e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Length</value>
      <webElementGuid>7511a974-a743-4eef-be17-5947e0b6f792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Length</value>
      <webElementGuid>9b1fe0e2-ed8e-45c3-8cd0-c4a1584a661b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Length</value>
      <webElementGuid>6b2b748e-c8a1-4884-ac29-26bdf26edbaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Length&quot;)</value>
      <webElementGuid>12629408-deba-4a3f-9cdb-4d8510ab7bcf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Length']</value>
      <webElementGuid>d9f671e7-3380-4a29-88cc-0c70917659d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='productTable']/thead/tr/td[4]/div/div/input</value>
      <webElementGuid>9f8fe1a5-32a9-4007-b6a6-98d414edd311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/div/input</value>
      <webElementGuid>665a48a1-81ef-45a7-bdf2-bf2711f10d5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @title = 'Length' and @name = 'Length' and @id = 'Length' and @placeholder = 'Length']</value>
      <webElementGuid>0ad8e189-a6dc-41f5-93a3-9f25159a0138</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
