<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__alternateuomvalue</name>
   <tag></tag>
   <elementGuidId>37d7329e-dd00-411b-b511-89621249028c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='alternateuomvalue']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#alternateuomvalue</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter Alternate Uom Value&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>84e3f685-004f-4f05-b5b3-13be19d675ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6a863420-5042-4a8c-a776-ccffad177d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control uof-width ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>b195a2a3-e958-462c-a7fe-92ab8910d48f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>34cd68ff-d4bc-42a8-b092-06d4f51bea3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>alternateuomvalue</value>
      <webElementGuid>c652506a-f34d-4c7f-aedb-0dadf77b6072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alternateuomvalue</value>
      <webElementGuid>74293ef7-006c-4e6c-9175-223b4ee10e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>01438246-9978-4c5c-acb5-aa0d22b21a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>alternateuomvalue</value>
      <webElementGuid>7c442a43-0492-4694-ad4c-ebaf55df2050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>if(!this.value.match('^[1-9][0-9]*$'))this.value='';</value>
      <webElementGuid>3853514e-d905-4a93-a081-0174715e69c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[1-9][0-9]*$</value>
      <webElementGuid>f3b8a314-4cbd-40b0-aced-1ce9e4f66ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fdc2f972-fe2a-4f00-bca9-59453b6e6dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>24491743-5c06-49b3-badb-f605192a5359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-pattern</name>
      <type>Main</type>
      <value>^[1-9][0-9]*$</value>
      <webElementGuid>28fbeb91-3dcc-4af6-934e-5326c1825e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>alternateuomvalue</value>
      <webElementGuid>ee3aa300-077e-4ab7-b292-8ad441d329a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Alternate Uom Value</value>
      <webElementGuid>37018c85-fe8f-411d-89e7-14d722b6dd44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alternateuomvalue&quot;)</value>
      <webElementGuid>121744d1-5ca1-4692-9ecd-780c1b81f658</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='alternateuomvalue']</value>
      <webElementGuid>4e320f36-ab35-4751-b5ea-a9f2891709cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='Qty_add_row']/td[4]/input</value>
      <webElementGuid>d04bb78c-cfde-4169-b23f-4eb96b7b4d3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input</value>
      <webElementGuid>9ba1fa2f-5b0c-4c35-a6e7-c187e18bda28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'alternateuomvalue' and @name = 'alternateuomvalue' and @type = 'text' and @placeholder = 'Enter Alternate Uom Value']</value>
      <webElementGuid>95c053b6-2e9c-4141-bde4-97282f43e65c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
