<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ALTERNATE UOM_baseuomvalu</name>
   <tag></tag>
   <elementGuidId>ef7f2792-6a43-4929-936f-02aee4fd2e3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='baseuomvalu']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#baseuomvalu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter Base Uom Value&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b580233d-cfdc-4cbd-950d-305a20386046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>30f33dd4-7433-41d1-983f-07aed33744fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control uof-width ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>870ee3bf-f4aa-4cca-aa00-e69d037224bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>0b023863-ebca-4a32-aea9-e55624c3fcc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>baseuomvalu</value>
      <webElementGuid>2bfc1504-d99e-48f5-a98c-f9c0f47a4322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>baseuomvalu</value>
      <webElementGuid>e0e9619c-aab3-4111-a7bc-04cb7fa52e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>14546be9-9ff8-4800-a9d6-bd89b7e1570f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>baseuomvalu</value>
      <webElementGuid>da0b39bb-af3e-40c3-861e-e5b817523f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>if(!this.value.match('^[1-9][0-9]*$'))this.value='';</value>
      <webElementGuid>faf5300a-ec12-453b-bde6-7b4ad72a64ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[1-9][0-9]*$</value>
      <webElementGuid>b4cabda7-caec-4ee5-a32f-2c5d913b0ed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ae4d18fa-b327-48ba-aa73-87fff3ec054c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>7660909d-2898-42c3-9647-528afcaa71dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-pattern</name>
      <type>Main</type>
      <value>^[1-9][0-9]*$</value>
      <webElementGuid>f472a0c6-06a3-42d1-9b7f-6b7f579ad4cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>baseuomvalu</value>
      <webElementGuid>a5aa4686-72be-45bd-8c8b-100fcc355e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Base Uom Value</value>
      <webElementGuid>09881161-d94c-4287-82d6-eff3b15aba2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;baseuomvalu&quot;)</value>
      <webElementGuid>ec46e464-0842-4eda-96e3-7aefe7ac2216</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='baseuomvalu']</value>
      <webElementGuid>5a34063c-0091-4a90-a420-b150684bdb3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='Qty_add_row']/td/input</value>
      <webElementGuid>70aed9b7-8d7b-4b8e-8e48-3eff8b00223c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>799fbe19-a80e-41fc-ab7e-31a5e6ba4466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'baseuomvalu' and @name = 'baseuomvalu' and @type = 'text' and @placeholder = 'Enter Base Uom Value']</value>
      <webElementGuid>9519cbcd-e965-4e89-8908-d916d5b118e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
