<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Default Buffer Stock_uintTextBox</name>
   <tag></tag>
   <elementGuidId>aa60b4e2-1158-47dd-af53-7d8f99c6b4c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='uintTextBox'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ng-star-inserted > div.col-md-3.col-sm-3.form-group.ng-star-inserted > #uintTextBox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#test6 #uintTextBox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2065d5b2-1b34-4b62-96ac-4cdea704211d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-field form-control numeric-text-right ng-pristine ng-valid ng-touched</value>
      <webElementGuid>56c4bc2a-3dce-4987-a32c-c2c3c43e347e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>bufferStock</value>
      <webElementGuid>9793896e-4af8-4c10-bf86-f3e48b31499a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uintTextBox</value>
      <webElementGuid>f067a0dd-1e65-477f-829b-9b2e40856a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>2f7c8545-351c-4b78-8b2c-9cf2848edb6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value=this.value.replace(/[^0-9]/g, '')</value>
      <webElementGuid>158d80b1-7ed4-4bd6-a036-de43fbcf0056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f75b6778-0a72-4732-bef5-ac890fcfbd43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e4a34e89-0d18-48b7-9b9e-543064f4cb32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>18d3e20f-99e9-4edd-8de4-376191503053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>bufferStock</value>
      <webElementGuid>ef49e565-b8b9-4294-9e11-7a8d43bac1c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;test6&quot;)/div[@class=&quot;row template-form-white-background template-form-inside-padding3 displFlex&quot;]/div[@class=&quot;col-md-9 col-sm-9 template-forms-inputs-labels no-padding&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;col-md-3 col-sm-3 form-group ng-star-inserted&quot;]/input[@id=&quot;uintTextBox&quot;]</value>
      <webElementGuid>d67d5f72-c0a7-4169-8887-71fcd5d2ed03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='uintTextBox'])[4]</value>
      <webElementGuid>f606dc74-27b9-4ce5-bbc1-3bdcf1981359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='test6']/div[2]/div/div[17]/div/input</value>
      <webElementGuid>5022abf4-3952-4b7c-9694-b201fd566e9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div/input</value>
      <webElementGuid>5cfbf6c1-a60d-44ae-b654-9f13405ef63f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'uintTextBox' and @type = 'text']</value>
      <webElementGuid>a1347290-e3a5-4849-aa5e-df9bd5b4ede8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
