<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UOM Set Name_uomset</name>
   <tag></tag>
   <elementGuidId>a468c579-dad9-4703-b16d-6eb3e55a212d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uomset']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uomset</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter Unique Uom Set Name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aed50c1f-3aad-4580-a25c-4aacf1cb2c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>382842a4-3b7c-4c6e-84b3-84ddc5ef0385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control uom-width ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>f2c84be9-118b-4088-993d-0e4a0f1ab521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>alphanumericspecial</value>
      <webElementGuid>9920504d-82eb-4eef-8acc-24977aecf1a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>uomset</value>
      <webElementGuid>936c6b6a-d353-4734-9ca9-337f9850f8da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uomset</value>
      <webElementGuid>a8c5ac6c-b21a-4225-ac76-ad081ecb7b5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>994c6cce-0f96-4f0d-82cb-ddbd4798dd3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>uomset</value>
      <webElementGuid>b9b2593e-fb63-4639-a749-52d737f80957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return (event.charCode > 96 &amp;&amp; event.charCode &lt; 123) 
                || (event.charCode > 64 &amp;&amp; event.charCode &lt; 91) || (event.charCode >= 48 &amp;&amp; event.charCode &lt;= 57) || event.charCode &lt;= 31</value>
      <webElementGuid>5c4b7506-1930-4398-aed6-e260bd016f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eb38b7df-26f8-46a4-acb0-f455e2dee8bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>5bd0f634-e782-47e2-a797-b38021f3b7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>uomset</value>
      <webElementGuid>4dedf029-07fa-4153-bbc1-431599b204bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Unique Uom Set Name</value>
      <webElementGuid>838b054f-68ed-4023-8e79-eb4df3dde8be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Charge Model Name</value>
      <webElementGuid>439c5acb-fc0c-4f30-8985-ae1809af065c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uomset&quot;)</value>
      <webElementGuid>81e21655-39fb-4988-81b7-cf796fc07c98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uomset']</value>
      <webElementGuid>571b767c-7e1a-4fd3-b919-fa8273c0aff6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='companyForm']/form/div[2]/div/div/div/div/input</value>
      <webElementGuid>a1bed280-7af9-4a50-8faf-79a24fff5106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>72377099-be29-4131-a5f9-e49aa4c5fc13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'uomset' and @name = 'uomset' and @type = 'text' and @placeholder = 'Enter Unique Uom Set Name']</value>
      <webElementGuid>8e0244b2-5c91-486c-bfb0-c01587437236</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
