<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__floatTextBox_1</name>
   <tag></tag>
   <elementGuidId>cacda78b-c554-4a7c-8f34-228ab49bc0b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='floatTextBox'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-9.col-sm-9.template-forms-inputs-labels.no-padding > div.col-md-3.col-sm-3.col-lg-3.form-group.ng-star-inserted > #floatTextBox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Gross Weight \(gms\) \*$/ >> #floatTextBox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a677c4f-a755-4008-b708-48f47a795fac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-field-wid-ht form-control numeric-text-right ng-untouched ng-dirty ng-valid</value>
      <webElementGuid>6432d620-f490-4ef1-94ab-ac15ad3da1ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>grossWeight</value>
      <webElementGuid>6ca40327-c9a1-409a-b66c-22dbfeae90dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>floatTextBox</value>
      <webElementGuid>dc531eb1-6632-4314-8da7-82d5ecb3eb24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>bb5359eb-5008-4e5c-a693-240e4d2d1e99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value=this.value.replace(/[^0-9]/g, '')</value>
      <webElementGuid>4713cb96-ba9c-4774-acca-0d582e85691d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a46de38b-4bd7-46ff-92c7-4859be9597e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>9baaae77-786c-4e18-927e-48f15ba90966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>grossWeight</value>
      <webElementGuid>53729801-7f44-4bc5-964e-aedf040566e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;test3&quot;)/div[1]/div[@class=&quot;row template-form-white-background template-form-inside-padding33 displFlex&quot;]/div[@class=&quot;col-md-9 col-sm-9 template-forms-inputs-labels no-padding&quot;]/div[@class=&quot;col-md-3 col-sm-3 col-lg-3 form-group ng-star-inserted&quot;]/input[@id=&quot;floatTextBox&quot;]</value>
      <webElementGuid>23a7ec30-1260-4e47-8640-b3b1b8326292</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='floatTextBox'])[5]</value>
      <webElementGuid>7a09b8d9-cad9-48d4-99eb-f41c866ce1ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='test3']/div/div[2]/div/div[65]/input</value>
      <webElementGuid>be2e2b69-43cc-4583-add1-c7d50f291104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[65]/input</value>
      <webElementGuid>6428fedb-03f1-47df-aa25-29f0e16b64d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'floatTextBox' and @type = 'text']</value>
      <webElementGuid>e6cd0b41-bae2-459c-b574-dfa968dbfb98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
