<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cost Price_costPrice</name>
   <tag></tag>
   <elementGuidId>d4b11d58-6d93-492a-873f-1c48e61eaff4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='costPrice']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#costPrice</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#costPrice</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>468d492d-7618-4df5-a01d-08e8f0649906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control numeric-text-right ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>33a2e75f-0a6f-4642-80be-80d211e1693c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>costPrice</value>
      <webElementGuid>e9d87771-5db2-46a0-a1ef-739f3eddb05a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>costPrice</value>
      <webElementGuid>1c79d599-402d-48d5-8259-76aefc454906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>c08de3b4-dff3-466f-bdc7-2f01142038b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>costPrice</value>
      <webElementGuid>d0a6fb16-b3bf-4205-8374-1b93c5774e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value=this.value.replace(/[^0-9]/g, '')</value>
      <webElementGuid>f6aa2129-dbec-442d-9233-5f3e4998f11b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>33f1119d-63ad-4051-9b13-a348dae483ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ee1af5d6-72cb-4e39-8693-d82b4c3941cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>7c3b8b79-fe92-4e95-b708-3d3bd9f7c2a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>costPrice</value>
      <webElementGuid>52c4dfe8-7926-4a51-891c-eb13b09b13bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;costPrice&quot;)</value>
      <webElementGuid>c6850d6b-9ade-4146-9964-cfda85126a8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='costPrice']</value>
      <webElementGuid>5f5c385a-5d33-4e01-98b4-3f4f8935262b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='test6']/div[2]/div/div[16]/div/input</value>
      <webElementGuid>3de3115a-3322-4776-9c8d-6b5771253a36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/input</value>
      <webElementGuid>4d632bf8-24a7-4c61-9685-9534f660ae97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'costPrice' and @name = 'costPrice' and @type = 'text']</value>
      <webElementGuid>96468a42-5aff-4a08-901a-d64404e472b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
