<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sales Price_salesPrice</name>
   <tag></tag>
   <elementGuidId>265c3de2-4365-400c-9a6a-5e1877f306fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='salesPrice']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#salesPrice</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#salesPrice</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9edf5fed-3ada-4125-be75-ce7af8ec6c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control numeric-text-right ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>3238cb85-4a2e-4e68-b1d2-70ecf320f762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>rrp</value>
      <webElementGuid>ebcaa422-cbfa-40d5-b494-a303dfd34fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>salesPrice</value>
      <webElementGuid>d885c815-ee5d-4c59-a482-418e5962f2f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>40e1887b-f6fe-4c89-aa81-7ebcbe4ddf0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>salesPrice</value>
      <webElementGuid>d7d79803-4e38-411d-be21-742cb2a82e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value=this.value.replace(/[^0-9]/g, '')</value>
      <webElementGuid>3d6d294d-9f6e-4e37-95e2-1afa88881b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8b02113d-4345-4802-95d5-4f2b0bcc6896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fb781ffd-72da-4290-b8b1-963fad583d53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>458dd646-3bf7-4c17-a9c9-bcdb6b9e6849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>rrp</value>
      <webElementGuid>dfc3ec63-c840-4a03-8dd3-f1c107800e22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;salesPrice&quot;)</value>
      <webElementGuid>670985a1-49a5-4bf3-aee0-cdc530898994</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='salesPrice']</value>
      <webElementGuid>279cfb80-d5b9-43df-9a05-85eec68375fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='test6']/div[2]/div/div[14]/div/input</value>
      <webElementGuid>af7018fc-de29-431c-b400-d2a70421168c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/input</value>
      <webElementGuid>0f43f6f1-103c-4dbc-9061-8c1a469ac50e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'salesPrice' and @name = 'salesPrice' and @type = 'text']</value>
      <webElementGuid>5be2ec9e-7ecb-467e-8bc0-c05aed9cc67f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
