<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Cash</name>
   <tag></tag>
   <elementGuidId>ca46a7ca-6cba-40ed-ad88-18b2c52c44cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content-chekout']/div/div/div[2]/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Cash&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>b27a7307-4a63-4c6c-bc93-e19b8276fcf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>payment-text</value>
      <webElementGuid>7cf2ee1c-349f-495e-9931-629b143d62e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Cash</value>
      <webElementGuid>fbe58303-b086-42f2-a334-e79f01455eb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content-chekout&quot;)/div[@class=&quot;col-sm-8 col-md-8 col-lg-8 no-padding&quot;]/div[@class=&quot;col-sm-12 col-md-12 col-lg-12 payment-tab-section&quot;]/div[@class=&quot;col-xl-3 col-lg-3 col-sm-4 col-xs-4 payment-card-padding ng-star-inserted&quot;]/div[@class=&quot;payment-card-list-tab&quot;]/p[@class=&quot;payment-text&quot;]</value>
      <webElementGuid>7ceb9321-e16a-41ee-a608-794e184c66c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-chekout']/div/div/div[2]/div/p</value>
      <webElementGuid>b09d1701-9049-4ea7-af8d-2564ecb18ce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADIDAS'])[1]/following::p[2]</value>
      <webElementGuid>00778244-7d28-42c9-8fb0-69c1003902ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Received Payment'])[1]/preceding::p[18]</value>
      <webElementGuid>33d3ec63-cfb3-43ba-9fb2-8db1b1ea0725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Received Payment Details Found!'])[1]/preceding::p[18]</value>
      <webElementGuid>4f456e5b-11cd-4fb7-8648-c7e1829b2c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cash']/parent::*</value>
      <webElementGuid>64fc1847-e97e-4368-b097-2080a6cce2a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p</value>
      <webElementGuid>9cb69db9-71c0-46c9-90e1-734840d648da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = ' Cash' or . = ' Cash')]</value>
      <webElementGuid>cd9ca332-f99d-42ff-bce6-fc40b2f0420c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
