<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path_Product Qty_Path_6168</name>
   <tag></tag>
   <elementGuidId>3a2c7134-7fba-4759-8119-ab4eac375170</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Path_6168</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;productsearch&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//*[@id=&quot;productsearch&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>45c0f195-9792-460c-b3e2-ea7fad3e51b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M23.358,13.476l-21.127.176a1.059,1.059,0,0,0-1.079,1.01l-.106,11.81a1.016,1.016,0,0,0,1.06.992l21.127-.176a1.059,1.059,0,0,0,1.079-1.01l.107-11.81a1.016,1.016,0,0,0-1.061-.992</value>
      <webElementGuid>12af754d-fd9f-4b4b-b1ee-b3d406b41e78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>Path 6168</value>
      <webElementGuid>4467e5b9-37d2-445e-ab42-108d9eaa2f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#33c481</value>
      <webElementGuid>a1ef072d-68b1-4365-b3ab-7e10c9bc56df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Path_6168</value>
      <webElementGuid>270466ca-cbd2-4829-b21e-90c0373420b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>transform</name>
      <type>Main</type>
      <value>translate(-0.306 -3.938)</value>
      <webElementGuid>31771756-883c-458a-9672-1048b729600f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Path_6168&quot;)</value>
      <webElementGuid>ed8473ab-6d26-48e7-ba04-d77ad1fb6b77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>c1ecdcff-0ff6-44be-96cb-34ae75cdd046</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
