<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_BATAPROCUREMENTGROUP</name>
   <tag></tag>
   <elementGuidId>420f0fc5-78e2-41c5-85fc-b7c0b10a32b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-200']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-200 > span.mat-option-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;BATAPROCUREMENTGROUP&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>59c9ad10-07d5-483f-ba1c-ac666fd05ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>9841bf81-1f19-48a1-9185-ff66832037aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BATAPROCUREMENTGROUP </value>
      <webElementGuid>968d55e0-9fe0-4e1a-83bc-4f723a3777e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-200&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>38b86c9a-b57b-4818-b46b-2cc4d3c9f28a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-200']/span</value>
      <webElementGuid>b3ded1ae-43e3-4513-9b13-b08832b3d316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--Select Procruement Group--'])[2]/following::span[1]</value>
      <webElementGuid>f7be751f-41b3-4133-b111-4892d11183d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Procurement 1'])[1]/preceding::span[1]</value>
      <webElementGuid>be650608-65a7-4fbf-9ff8-02c3008d2dd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='R Procurement Group'])[1]/preceding::span[2]</value>
      <webElementGuid>bde4ced6-b59e-479d-90fa-7ac817ca975d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BATAPROCUREMENTGROUP']/parent::*</value>
      <webElementGuid>41169fc0-6228-4f25-89f9-589e2c03c966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[2]/span</value>
      <webElementGuid>94a34ea2-d2ed-4f62-a3c6-1807582a4352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'BATAPROCUREMENTGROUP ' or . = 'BATAPROCUREMENTGROUP ')]</value>
      <webElementGuid>60a14832-661a-4de1-be71-b3f8b271345d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
