<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Casio G-Shock Watches 3 (8963432)</name>
   <tag></tag>
   <elementGuidId>16d9c1c2-090c-4c27-b79b-f055bb755d5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-35']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-35 > span.mat-option-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Casio G-Shock Watches 3 (8963432)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c0e5e19a-1601-49d0-afed-233bc54fe332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>382f630b-9e81-455f-bae7-b646a52c45d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Casio G-Shock Watches 3 (8963432)</value>
      <webElementGuid>861be7dc-fe01-4b3e-9786-bdd73469ec4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-35&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>ca9fc1ce-6498-47bf-83e1-151b645b41f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-35']/span</value>
      <webElementGuid>3d1d6750-314c-4d8c-a256-808f7e3b3661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(BW001)'])[1]/following::span[1]</value>
      <webElementGuid>b78d60f9-ed40-4cae-a4aa-c0a98d66eb31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Casio G-Shock Watches 3']/parent::*</value>
      <webElementGuid>0ae7777b-0330-4dab-8ea8-c996cfa56e2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[5]/span</value>
      <webElementGuid>740c33e6-6cc4-47d7-ac23-b93a2d8b9f31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Casio G-Shock Watches 3 (8963432)' or . = ' Casio G-Shock Watches 3 (8963432)')]</value>
      <webElementGuid>b5d38bf0-ccb2-4f0e-9195-af19e64eccd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
