<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ADIDAS</name>
   <tag></tag>
   <elementGuidId>2fb498a8-5cf7-4639-bf15-9777d07d7c5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='--Select Brand--'])[2]/following::span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-125 > span.mat-option-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;ADIDAS&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ab00b412-3275-41c7-8f8f-a913dd795f90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>dbda5aac-8abf-4f50-b9ca-ab0ca0f2ca91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ADIDAS </value>
      <webElementGuid>e52c43e9-fbd6-4345-8e77-c1ee7e7ec868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-125&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>943263a6-2b8e-4816-8866-f9ce5e57df8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-125']/span</value>
      <webElementGuid>1b71a79c-189e-440a-a743-44324c39c64b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--Select Brand--'])[2]/following::span[1]</value>
      <webElementGuid>1061bca8-31f3-47b3-bb6a-3ea47abdd9f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALLEN SOLLY'])[1]/preceding::span[1]</value>
      <webElementGuid>7296f922-4b27-4c3e-bb4b-e1608dc06dd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AquaGlow'])[1]/preceding::span[2]</value>
      <webElementGuid>ea6b2ce4-b8b6-49d8-8f1b-0a912e27c374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ADIDAS']/parent::*</value>
      <webElementGuid>885da27e-de68-4e1b-b0c5-3e0fe1a37428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[2]/span</value>
      <webElementGuid>990a89f9-2994-45b1-adbb-bed52fb57091</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'ADIDAS ' or . = 'ADIDAS ')]</value>
      <webElementGuid>0d7e014c-ef64-412a-ab9a-50dcb1869bbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
