<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_BND - Bundle</name>
   <tag></tag>
   <elementGuidId>d4fb567f-5c8a-4766-b021-dadbd8a1c2bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-56']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-56 > span.mat-option-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;BND - Bundle&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ad0941f1-b097-4651-aa48-0b16109ad01a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>3441e972-16e1-4d62-8d70-c7201226a6a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> BND - Bundle </value>
      <webElementGuid>048df81b-1aec-497e-acb5-a0f6937c4f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-56&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>f5f3f2fc-c214-4758-8554-92b9fd02d319</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-56']/span</value>
      <webElementGuid>0383e24b-b352-490f-80b4-7d57db895b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BKT - Bucket'])[1]/following::span[1]</value>
      <webElementGuid>3d82b5bb-4089-4797-bc1d-e57cb3e6ee6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BX - Box1'])[2]/following::span[2]</value>
      <webElementGuid>22cfa8b8-54bc-417b-a49a-04978fa6489a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BND - Bundle2'])[1]/preceding::span[1]</value>
      <webElementGuid>3f93c9ec-9dc5-4d03-87dd-d65cde84b7d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CRD - Card'])[1]/preceding::span[2]</value>
      <webElementGuid>6b23da61-c612-4f1e-86f8-2a5e48c0c62c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BND - Bundle']/parent::*</value>
      <webElementGuid>35935124-c326-4fea-8d59-3439f4985cd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[5]/span</value>
      <webElementGuid>e69d30ce-e4a9-4482-882a-356347205490</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' BND - Bundle ' or . = ' BND - Bundle ')]</value>
      <webElementGuid>0411b255-507e-4d93-86cd-ce2e59ed7fe4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
