<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__text-field form-control textarea-_f7e447</name>
   <tag></tag>
   <elementGuidId>59563222-bef6-4ce7-9299-ead9e2667044</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@type='text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea.text-field.form-control.textarea-height.ng-untouched.ng-invalid.ng-dirty</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>textarea[type=&quot;text&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8f778c6a-e266-4bba-9897-0f59cbf463a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-field form-control textarea-height ng-untouched ng-invalid ng-dirty</value>
      <webElementGuid>d274bebb-2981-4fc0-a99f-72906f95a327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>6f25d04e-be5d-4e4e-903a-e6e233449213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>productName</value>
      <webElementGuid>88e81c66-77e2-49ef-b737-273e09be5b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>905452d1-96d5-46e7-8702-bec8aea93c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>1637cb48-ad16-4a73-a408-f5a40224acb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>e6f74c69-bb01-4f53-b6a1-3a169623e622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e2798428-5162-4edd-9416-be46c787f095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-minlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>2e9becdf-2598-42e8-bd7a-b2ce2bc1f294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>f3ec2a60-27bd-4ea4-8314-631717fb6777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>productName</value>
      <webElementGuid>6f43113a-ab50-478f-9ed6-a3830116babe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;test1&quot;)/div[1]/div[@class=&quot;row template-form-white-background template-form-inside-padding-first&quot;]/div[@class=&quot;row displFlex&quot;]/div[@class=&quot;col-md-9 col-sm-9 template-forms-inputs-labels fields lables-step-1&quot;]/div[@class=&quot;col-md-6 col-sm-6 col-lg-6 form-group ng-star-inserted&quot;]/textarea[@class=&quot;text-field form-control textarea-height ng-untouched ng-invalid ng-dirty&quot;]</value>
      <webElementGuid>525bcad2-c546-4465-8289-d52f6f303956</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@type='text']</value>
      <webElementGuid>6f805eab-f8bd-43fa-ace8-c898cddaf939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='test1']/div/div[2]/div/div/div[4]/textarea</value>
      <webElementGuid>9586461c-c934-4c78-b1c7-9c432a6b13b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>03c7799d-1073-4d6c-9844-23563b7bf9de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@type = 'text']</value>
      <webElementGuid>7e0889eb-21ca-4c3e-9ff5-b2c97d52fccb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
