<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Product Master</name>
   <tag></tag>
   <elementGuidId>57172237-e3c5-40ea-afc4-f70aa7a91eec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='products_div']/ul/li[3]/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Product Master&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0e4549f9-b111-4700-a639-cd2fc705bff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sub-menu-heading sub-menu-font-size</value>
      <webElementGuid>5989a0d5-6735-4f5d-9e10-29008fde1aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link</name>
      <type>Main</type>
      <value>product/master/list</value>
      <webElementGuid>c79dd23a-5149-4e5a-984d-7d7bd3cbd830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/product/master/list</value>
      <webElementGuid>01e18a39-5d98-4626-bc56-d9284251351e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Product Master</value>
      <webElementGuid>5a6dd594-43a1-4de5-8626-e54dfa27de32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;products_div&quot;)/ul[1]/li[@class=&quot;ng-star-inserted&quot;]/ul[1]/li[@class=&quot;sub-menu-full ng-star-inserted&quot;]/a[@class=&quot;sub-menu-heading sub-menu-font-size&quot;]</value>
      <webElementGuid>65073bcd-9640-4f9b-8f1d-5c6eabe6ecd3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='products_div']/ul/li[3]/ul/li[2]/a</value>
      <webElementGuid>f4d927db-21a2-4464-b902-1054efa10739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Product Master')]</value>
      <webElementGuid>9eaf203e-014e-4fe6-bf1b-16b0e8fbcb8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Catalog'])[1]/following::a[1]</value>
      <webElementGuid>fcc09e7e-b79d-491d-bd17-99d0f83d8e9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PRODUCT MANAGEMENT'])[2]/following::a[2]</value>
      <webElementGuid>746b5f13-8fe4-4f4c-bdfe-b695304042a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Alias'])[1]/preceding::a[1]</value>
      <webElementGuid>db0a3c01-3508-430a-b86d-dc9b1fcaadaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UOM Conversion'])[1]/preceding::a[2]</value>
      <webElementGuid>ad039c71-efdf-4b73-a2f1-5114edd99bcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Product Master']/parent::*</value>
      <webElementGuid>caeaeee8-a6a2-4b0a-93c8-0248791c3d1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/product/master/list')]</value>
      <webElementGuid>17aeaec7-4fc0-483a-9465-bbd8b550bdae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a/div/ul/li[3]/ul/li[2]/a</value>
      <webElementGuid>6a21aa7f-a78a-404e-a87e-f20b2fc8ba14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/product/master/list' and (text() = 'Product Master' or . = 'Product Master')]</value>
      <webElementGuid>26cc3bbc-bdf4-4bdd-a558-875dab1ec2ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
