<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_UPDATE</name>
   <tag></tag>
   <elementGuidId>93d0789c-eaa3-4c12-932b-9427964d973f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-non-phone']/li/ul/li[3]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.hb-save-btn.hb-ripple.node-hb-save-btn.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;UPDATE&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>aaf0c9bd-6672-4915-9e96-e0fdd2ef8305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hb-save-btn hb-ripple node-hb-save-btn ng-star-inserted</value>
      <webElementGuid>7e624b34-bc1c-401f-8315-e791dba0ca43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> UPDATE </value>
      <webElementGuid>45fb1a63-ab21-410f-a346-83423e234d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-non-phone&quot;)/li[1]/ul[1]/li[@class=&quot;has-search ng-star-inserted&quot;]/button[@class=&quot;hb-save-btn hb-ripple node-hb-save-btn ng-star-inserted&quot;]</value>
      <webElementGuid>8aab2a62-507a-4e0f-9e0b-f8866aedad4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-non-phone']/li/ul/li[3]/button</value>
      <webElementGuid>9fe8404d-3a61-4317-8f1f-fb7e44bcdfc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DISCARD'])[1]/following::button[1]</value>
      <webElementGuid>b69951be-0435-47d8-a445-b581d0433d28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit UOM Set'])[1]/following::button[3]</value>
      <webElementGuid>24ce7092-a11d-4cbc-81b3-ebb35a5421db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DISCARD'])[2]/preceding::button[1]</value>
      <webElementGuid>2426de1d-3ae8-43a3-9230-5629ea6b03a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UPDATE'])[2]/preceding::button[2]</value>
      <webElementGuid>644e0f31-fd45-4e2a-a4cf-58078b8a0732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='UPDATE']/parent::*</value>
      <webElementGuid>7069ad81-150e-4a5c-b674-146c9a632007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/button</value>
      <webElementGuid>d742d075-1262-41a0-89f4-dd73cf2b5e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' UPDATE ' or . = ' UPDATE ')]</value>
      <webElementGuid>372a4823-a38d-4a51-8f03-56ec501a8208</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
