<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SINGLE PRODUCT</name>
   <tag></tag>
   <elementGuidId>da111365-2c7e-4e21-addd-560734b54d64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='prod-master-main-list']/div/div[4]/div/div[2]/div/div/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.add-btn-popup-second-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;SINGLE PRODUCT&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>811bf2f8-da00-4b1a-a206-c6bdde0375e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>add-btn-popup-second-btn</value>
      <webElementGuid>36e34766-cca5-441c-b811-1d87ec4ec3ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> SINGLE PRODUCT </value>
      <webElementGuid>4f1e444b-f165-4d3f-b16a-c3652151f1e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prod-master-main-list&quot;)/div[@class=&quot;container-fluid ng-star-inserted&quot;]/div[@class=&quot;margin-content&quot;]/div[@class=&quot;row&quot;]/div[2]/div[@class=&quot;hb-position-relative ng-star-inserted&quot;]/div[@class=&quot;add-btn-popup-section&quot;]/button[@class=&quot;add-btn-popup-second-btn&quot;]</value>
      <webElementGuid>7f9cf21e-4a75-481e-950d-243bdee8f3c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='prod-master-main-list']/div/div[4]/div/div[2]/div/div/button[2]</value>
      <webElementGuid>9b03f87a-aa79-476e-a7ca-cea47993852c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PRODUCT UPLOAD'])[1]/following::button[1]</value>
      <webElementGuid>748111d8-6ea1-4129-9b9f-bc246f54fca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[18]/following::button[2]</value>
      <webElementGuid>fbcd6d9a-0f87-46a4-a1fe-1933ddc27f1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status Progress'])[1]/preceding::button[2]</value>
      <webElementGuid>85f2eb28-6c99-4d2a-adbd-710a32591119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::button[2]</value>
      <webElementGuid>ff35659c-9f8f-4204-b74c-d2745a15b9f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SINGLE PRODUCT']/parent::*</value>
      <webElementGuid>4ea1e102-df6b-477a-b30c-9affa8a1af3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button[2]</value>
      <webElementGuid>cc7c67c9-7b16-4898-aab7-a94813cf70e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' SINGLE PRODUCT ' or . = ' SINGLE PRODUCT ')]</value>
      <webElementGuid>7e4690bc-f789-4768-9c1b-4a8c0dddb2db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
