<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_--Select Pricepoint--</name>
   <tag></tag>
   <elementGuidId>6581f121-3f35-4bbe-a3f7-b5f6e90b01af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-select[@id='mat-select-15']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-select-15 > div.mat-select-trigger > div.mat-select-value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;--Select Pricepoint--&quot;i >> div >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c7293dc2-67c0-41e5-bd90-bdf5f57b34c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-value</value>
      <webElementGuid>5f82efd4-8d91-4518-a064-11ad8543d657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-switch</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>477598be-6ed1-4542-a6c9-f6daad9b649c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select Pricepoint--</value>
      <webElementGuid>e20a0ef3-874c-4292-b400-92dc128ce9b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-15&quot;)/div[@class=&quot;mat-select-trigger&quot;]/div[@class=&quot;mat-select-value&quot;]</value>
      <webElementGuid>b110c7a3-ecac-4586-aa0b-7825eb094a58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='mat-select-15']/div/div</value>
      <webElementGuid>a12901ac-a04e-4873-a9f2-bd2d7c7ac1b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[12]/following::div[2]</value>
      <webElementGuid>0b59252d-5634-4f5f-8dca-d4f5e703814e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[30]/div/mat-select/div/div</value>
      <webElementGuid>459892e4-164b-4aa1-a0aa-a507dea14edb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '--Select Pricepoint--' or . = '--Select Pricepoint--')]</value>
      <webElementGuid>77ed8dae-effc-4a56-ba97-afc07e7e3803</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
