<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Stock Take_4img</name>
   <tag></tag>
   <elementGuidId>6b592bf4-b338-45ae-8bd6-0bc67e62103d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='4img']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#4img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Product Management&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bbf1d10e-5a25-45e6-8cdf-e7107147be86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-menu-icons</value>
      <webElementGuid>66e425de-c48c-41e0-8649-5c7ff43ef9fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>4img</value>
      <webElementGuid>f3635854-88e0-4beb-99a2-669de17c6c0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../assets/images/icons/products.svg</value>
      <webElementGuid>da75071d-59d1-4daf-b3cf-455928a59c8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;4img&quot;)</value>
      <webElementGuid>18852bbd-13d2-4016-a09a-5102f7018612</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='4img']</value>
      <webElementGuid>45f6bd74-968b-4d0f-b9dd-6f77f964b9b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='products_anchor']/span/img</value>
      <webElementGuid>296ff656-a453-4201-aa6a-cd931473082e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a/span/img</value>
      <webElementGuid>56381058-051c-4a9b-80ec-49d635bf445a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = '4img' and @src = '../assets/images/icons/products.svg']</value>
      <webElementGuid>6bcb30c4-f772-4c38-ae1c-f774c67ffdab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
