<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UOM Set Name_uomset</name>
   <tag></tag>
   <elementGuidId>c029c6b3-d3e7-492c-8d6c-a3fc5be08aa3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uomset']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uomset</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter Unique Uom Set Name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>509c7bbf-7146-4285-af42-fed00f19f56a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>99d30bb7-f607-4a08-b9ec-650f431cc1c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control uom-width ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>04fa233e-b51c-42a7-aa37-d210a693aac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>alphanumericspecial</value>
      <webElementGuid>8c77d69c-2b7d-4428-850a-13484e65499a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>uomset</value>
      <webElementGuid>28caeea8-338c-46c5-9ac2-093247006971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uomset</value>
      <webElementGuid>504ad8b9-5e6f-4bfc-94ff-2c8847c30b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>88bf1704-13a6-4541-9a59-1a7c3ebfd7fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>uomset</value>
      <webElementGuid>e6c0a661-c7e7-4113-84c7-80550cdb46bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return (event.charCode > 96 &amp;&amp; event.charCode &lt; 123) 
                || (event.charCode > 64 &amp;&amp; event.charCode &lt; 91) || (event.charCode >= 48 &amp;&amp; event.charCode &lt;= 57) || event.charCode &lt;= 31</value>
      <webElementGuid>a12efb4b-6506-4c82-8e19-1d27ef9a1f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d0d67280-82f0-409c-a608-b1abd09a8e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>78ab7410-e40b-43da-bbe3-ff08dd039c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>uomset</value>
      <webElementGuid>296a54cc-fd68-42a0-b21e-7e0663dd7e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Unique Uom Set Name</value>
      <webElementGuid>5bb60734-63ed-4a1a-ae65-f29cda44a301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Charge Model Name</value>
      <webElementGuid>95521fa2-25af-43d5-b51e-b70ed73330b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uomset&quot;)</value>
      <webElementGuid>07f16705-ba99-46e8-81a4-abad4c3b7875</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uomset']</value>
      <webElementGuid>52b2693d-acc6-41d0-b219-67aa127857ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='companyForm']/form/div[2]/div/div/div/div/input</value>
      <webElementGuid>55b81f84-c2c9-4cb4-b4d5-372d041b3f43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>5fe464b3-3b8b-439b-bb80-830d5fb67f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'uomset' and @name = 'uomset' and @type = 'text' and @placeholder = 'Enter Unique Uom Set Name']</value>
      <webElementGuid>10863611-ce44-46a0-9128-fdffeabf879b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
