<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-select_--Select Pricepoint--</name>
   <tag></tag>
   <elementGuidId>e5c50c7a-ddf4-4193-a14c-c4aaea953c6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-select[@id='mat-select-15']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-select-15</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;--Select Pricepoint--&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-select</value>
      <webElementGuid>e47cd498-42a3-4b95-8a81-c0f4f931728b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select ng-tns-c5-43 form-control text-field ng-untouched ng-pristine ng-valid mat-select-empty ng-star-inserted</value>
      <webElementGuid>7b0dfe40-679e-4d2a-8c9c-0bf5f356f774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>panelclass</name>
      <type>Main</type>
      <value>myPanelClass</value>
      <webElementGuid>b2fd80fd-0d31-4762-8885-48b591327e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>7c11a962-dfbc-42c1-9dfd-a634b1e60a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>form-control text-field </value>
      <webElementGuid>537893de-0db5-47f6-96a9-09e2757b72f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e5c34fe2-22bf-40dc-9e3c-2770a768859d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>pricePointId</value>
      <webElementGuid>2b75009c-4108-4593-8edf-d17249f39868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-panel-class</name>
      <type>Main</type>
      <value>myPanelClass</value>
      <webElementGuid>733006a6-ce83-4fb6-857b-5e4ad4936cc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-placeholder</name>
      <type>Main</type>
      <value>--Select Pricepoint--</value>
      <webElementGuid>6b1fe276-1c6e-4f80-8c46-539d817e84e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-select-15</value>
      <webElementGuid>a7c2162c-8561-4195-84bb-e6e57d99e93f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6c5bcd33-6ca8-4732-8ed0-498da7c24465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>--Select Pricepoint--</value>
      <webElementGuid>8a347158-55fa-4ef6-9476-ddb915828283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>798e55f6-b02d-44ae-a327-318526e44f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>72577e1e-6d4f-46f9-96d9-fcdfdee224f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0fc41312-3f44-4082-8093-43f01387d9ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiselectable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>59d5ced1-21e4-40f0-8a59-fe6d467945a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select Pricepoint--</value>
      <webElementGuid>76374dcd-689a-44b8-8dd8-fa40cf6cf1f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-15&quot;)</value>
      <webElementGuid>9a6e6c97-a04d-458a-acbb-fb469586d288</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-select[@id='mat-select-15']</value>
      <webElementGuid>4ee333bd-0d9c-45c8-98bf-15ed5c7955d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step2']/div[30]/div/mat-select</value>
      <webElementGuid>866513e6-4423-41b2-bef5-b331b494e34e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[12]/following::mat-select[1]</value>
      <webElementGuid>7a406f9d-5e0c-4412-a375-b5c08be2ae31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[30]/div/mat-select</value>
      <webElementGuid>65a7eccb-aad4-434b-a203-22637dea162d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-select[@id = 'mat-select-15' and (text() = '--Select Pricepoint--' or . = '--Select Pricepoint--')]</value>
      <webElementGuid>9f07a1a4-5d1d-46e8-bc28-9bfc345e5ded</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
