<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_visibility_off</name>
   <tag></tag>
   <elementGuidId>9f81bc71-c5ea-4339-af69-3e06a0d12f5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login-page-section']/div/div/form/div/div[2]/div/div[3]/div[2]/div/div/span/mat-icon</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>mat-icon.login-password-placeholder.mat-icon.notranslate.material-icons.mat-icon-no-color</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;visibility_off&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>8f3a1ca3-280a-4744-9d83-f72768c28056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-password-placeholder mat-icon notranslate material-icons mat-icon-no-color</value>
      <webElementGuid>2668d7b9-80b6-4352-900b-772f87dc27a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e3b8da0f-f344-4324-b730-571264b232f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b0c7a88f-7a38-40ff-8776-b4c03ec9895d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>visibility_off</value>
      <webElementGuid>1a09674e-fdb5-42a9-be25-cd2b3c411f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-page-section&quot;)/div[@class=&quot;login-container&quot;]/div[1]/form[@class=&quot;login-form-display-center ng-touched ng-dirty ng-valid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;row login-desktop-view topspace&quot;]/div[@class=&quot;col-lg-6 col-md-8 col-xs-10 col-lg-offset-3 col-md-offset-2 col-xs-offset-1&quot;]/div[@class=&quot;login-user-login-section&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-xs-12 hb-no-padding&quot;]/div[@class=&quot;hb-form-group&quot;]/div[@class=&quot;login-input-group&quot;]/span[@class=&quot;input-placeholder&quot;]/mat-icon[@class=&quot;login-password-placeholder mat-icon notranslate material-icons mat-icon-no-color&quot;]</value>
      <webElementGuid>b0201941-8813-4528-beca-645ff5a761e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-page-section']/div/div/form/div/div[2]/div/div[3]/div[2]/div/div/span/mat-icon</value>
      <webElementGuid>881256f5-f237-4cb6-be0c-a4421d72c006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/following::mat-icon[1]</value>
      <webElementGuid>277d4082-2609-42b2-a98a-20bb2e224a23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOGIN'])[1]/preceding::mat-icon[1]</value>
      <webElementGuid>9f0abeb8-f2d9-4e1d-8196-a86e822036b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password?'])[1]/preceding::mat-icon[1]</value>
      <webElementGuid>93651f43-8019-4b2d-83c8-0c5b110d4f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='visibility_off']/parent::*</value>
      <webElementGuid>6e3c7671-b8be-492c-a825-d433ba1b74e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-icon</value>
      <webElementGuid>91b73622-773e-4d47-8a0b-2f370b8b03ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = 'visibility_off' or . = 'visibility_off')]</value>
      <webElementGuid>5726dde0-e831-4744-b96e-7f7c29ce007e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
