<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Casual Watches  (3443322)</name>
   <tag></tag>
   <elementGuidId>1db1bb7a-a1e6-47ba-a153-9fbe093c64b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-38']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-38 > span.mat-option-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Casual Watches (3443322)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>299019a8-700f-4285-a90c-189168f4a107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>96a8f0a0-53fb-441a-aba7-99acccf5a589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Casual Watches  (3443322)</value>
      <webElementGuid>1cf26313-c10b-4218-bc12-cd57785b8f4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-38&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>ab411ad0-d58c-4b1f-9006-b42440509469</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-38']/span</value>
      <webElementGuid>945252a2-7953-4b86-8268-8a016a0d8153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(3143343221)'])[1]/following::span[1]</value>
      <webElementGuid>31a02c87-15a2-44ed-a7b6-c9c0f7af06fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Casual Watches']/parent::*</value>
      <webElementGuid>93281eae-cfb8-4a4b-9d5f-407dcb4a3852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[2]/span</value>
      <webElementGuid>fb4f838b-a7fe-4b0b-bcca-51aeaf49680d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Casual Watches  (3443322)' or . = ' Casual Watches  (3443322)')]</value>
      <webElementGuid>bbd342c5-61f6-4677-a171-78fbb720fb97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
