<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__text-field form-control textarea-_f7e447</name>
   <tag></tag>
   <elementGuidId>d20d0291-4c26-4885-a111-d0f0913ef466</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@type='text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea.text-field.form-control.textarea-height.ng-untouched.ng-invalid.ng-dirty</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>textarea[type=&quot;text&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c30fde43-9bbd-49db-b5f8-659273368206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-field form-control textarea-height ng-untouched ng-invalid ng-dirty</value>
      <webElementGuid>0bcb00a3-b8c3-48c5-a099-bbb1e5392e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>b2fa98ff-76f4-4674-a18b-37c2491bc2c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>productName</value>
      <webElementGuid>3945e14e-3105-4087-82a7-094f3f1d644d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>0ba806a2-65f5-464f-beba-efd53c8d9584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>cd233196-c3a5-4775-a75a-13f31d1acd09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>048dcfb4-3480-4f1c-91a0-c40a3c76c87d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cf3b41d4-fbd2-450f-937d-c59706e285dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-minlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>f156c17d-9e16-4290-a990-b2f32fa138c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>502a8946-c709-451e-86d7-6a048e7bd64e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>productName</value>
      <webElementGuid>74fa7d5d-d23c-402a-a2f6-09753c029b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;test1&quot;)/div[1]/div[@class=&quot;row template-form-white-background template-form-inside-padding-first&quot;]/div[@class=&quot;row displFlex&quot;]/div[@class=&quot;col-md-9 col-sm-9 template-forms-inputs-labels fields lables-step-1&quot;]/div[@class=&quot;col-md-6 col-sm-6 col-lg-6 form-group ng-star-inserted&quot;]/textarea[@class=&quot;text-field form-control textarea-height ng-untouched ng-invalid ng-dirty&quot;]</value>
      <webElementGuid>6946219b-0b27-4af7-bb76-d5be263c482d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@type='text']</value>
      <webElementGuid>e524707c-d559-4e16-b956-ede3758ef802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='test1']/div/div[2]/div/div/div[4]/textarea</value>
      <webElementGuid>6db208c1-44e4-4909-8e9b-25bd316da59e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>48d7367a-aa41-4a7c-9949-cea61a24066a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@type = 'text']</value>
      <webElementGuid>c5f2b2c0-9788-4eee-a329-57b8729ff050</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
